### ISSUE TITLE
MPC 3.6 or later download link for windows

### ISSUE THREAD

**Issue by SMTHBY** [objectcomputing/quickfast#141]
can anyone please share the download link for MPC 3.6 or later for windows. I need to build QuickFAST for .NET 
Does anyone have QUICKFAST dll for windows .NET 64 bit.

I am not getting MPC V 3.6 or later in below link.
 (http://www.ociweb.com/products/mpc)

Thank you.

**Comment by mitza-oci** [comment]
https://github.com/objectcomputing/MPC
